export default interface FitsSpectrum {
    filename: string,
    targetname: string,
    observed_at: string,
    type: string,
    subtype: string,
    ra: number,
    dec: number,
    magtype: string,
    mag_1: number,
    mag_2: number,
    mag_3: number,
    mag_4: number,
    mag_5: number,
    mag_6: number,
    mag_7: number,
    sn_u: number,
    sn_g: number,
    sn_r: number,
    sn_i: number,
    sn_z: number,
    z: number,
    z_err: number,
    wave: number[],
    flux: number[]
}